# Generated by Django 2.0.7 on 2018-07-08 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDoesntHavePermission',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('page_id', models.IntegerField()),
                ('object_id', models.IntegerField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Member.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupHavePermission',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('page_id', models.IntegerField()),
                ('object_id', models.IntegerField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Member.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('page_id', models.IntegerField()),
                ('object_id', models.IntegerField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Member.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
