# Generated by Django 2.0.7 on 2018-07-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageId', models.DecimalField(decimal_places=3, max_digits=3)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('id', 'name')},
        ),
    ]
