# Generated by Django 2.1.1 on 2018-09-29 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Member', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppermission',
            name='groupGivePerm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Member.Group_Give_Perm'),
        ),
        migrations.AddField(
            model_name='grouppermission',
            name='groupHavePerm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Member.Group_Have_Perm'),
        ),
        migrations.AddField(
            model_name='grouppermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouphavepermission',
            name='groupGivePerm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Member.Group_Give_Perm'),
        ),
        migrations.AddField(
            model_name='grouphavepermission',
            name='groupHavePerm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Member.Group_Have_Perm'),
        ),
        migrations.AddField(
            model_name='grouphavepermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupdoesnthavepermission',
            name='groupGivePerm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Member.Group_Give_Perm'),
        ),
        migrations.AddField(
            model_name='groupdoesnthavepermission',
            name='groupHavePerm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Member.Group_Have_Perm'),
        ),
        migrations.AddField(
            model_name='groupdoesnthavepermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='objectgroup',
            unique_together={('pageObject_id', 'group_id')},
        ),
        migrations.AlterUniqueTogether(
            name='object',
            unique_together={('className', 'page_id')},
        ),
        migrations.AlterUniqueTogether(
            name='grouppermission',
            unique_together={('page_id', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='grouphavepermission',
            unique_together={('page_id', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='groupdoesnthavepermission',
            unique_together={('page_id', 'object_id')},
        ),
    ]
