# Generated by Django 2.0.7 on 2018-07-10 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectId', models.DecimalField(decimal_places=3, max_digits=3)),
                ('className', models.CharField(max_length=40)),
                ('idName', models.CharField(max_length=40)),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Common.Page')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='object',
            unique_together={('className', 'page_id')},
        ),
    ]
