# Generated by Django 2.0.7 on 2018-07-11 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0002_group_for_objects'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Common.Group_For_Objects')),
                ('pageObject_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Common.Object')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='objectgroup',
            unique_together={('pageObject_id', 'group_id')},
        ),
    ]
