# Generated by Django 2.0.7 on 2018-07-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0002_auto_20180710_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_For_Objects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=20)),
            ],
        ),
    ]
