# Generated by Django 2.0.7 on 2018-07-10 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0003_group_for_objects'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Common.Group_For_Objects')),
            ],
        ),
        migrations.AlterField(
            model_name='object',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='object',
            unique_together={('className', 'idName')},
        ),
        migrations.AddField(
            model_name='objectgroup',
            name='pageObject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Common.Object'),
        ),
    ]
