# Generated by Django 2.0.7 on 2018-07-10 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0004_auto_20180710_1729'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='object',
            unique_together={('className', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='objectgroup',
            unique_together={('pageObject_id', 'group_id')},
        ),
    ]
