# Generated by Django 2.0.7 on 2018-07-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0005_auto_20180710_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='object',
            unique_together={('className', 'page_id')},
        ),
    ]
