# Generated by Django 2.0.7 on 2018-07-10 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Common', '0007_auto_20180710_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDoesntHavePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.IntegerField()),
                ('object_id', models.IntegerField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('groupGivePerm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Member.Group_Give_Perm')),
                ('groupHavePerm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Member.Group_Have_Perm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupHavePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.IntegerField()),
                ('object_id', models.IntegerField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('groupGivePerm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Member.Group_Give_Perm')),
                ('groupHavePerm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Member.Group_Have_Perm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='grouphavepermission',
            unique_together={('page_id', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='groupdoesnthavepermission',
            unique_together={('page_id', 'object_id')},
        ),
    ]
