# Generated by Django 2.0.7 on 2018-07-28 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_auto_20180725_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessages',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replyTo', to='Chat.RoomMessages'),
        ),
        migrations.AlterField(
            model_name='roommessages',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_messages', to='Chat.Room'),
        ),
        migrations.AlterField(
            model_name='roomusers',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_users', to='Chat.Room'),
        ),
    ]
