# Generated by Django 2.0.7 on 2018-08-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0005_auto_20180814_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberships',
            name='name',
            field=models.NullBooleanField(max_length=50),
        ),
    ]
