# Generated by Django 2.0.7 on 2018-08-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0007_auto_20180814_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberships',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
