# Generated by Django 2.0.7 on 2018-08-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicians',
            name='Expertise',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
