# Generated by Django 2.0.7 on 2018-08-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_physicians_expertise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
