# Generated by Django 2.0.7 on 2018-08-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0004_auto_20180813_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberships',
            name='name',
            field=models.CharField(choices=[(1, 'Gold'), (2, 'Bronz'), (3, 'Silver'), (4, 'Normal')], max_length=50),
        ),
    ]
