# Generated by Django 2.0.7 on 2018-08-19 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0005_auto_20180814_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='Profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='member_profile', to='Member.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='physician',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='member_physician', to='Member.Physicians'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expertises',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_membership', to='Member.Memberships'),
        ),
        migrations.AlterField(
            model_name='members',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='member_user', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='physicians',
            name='expertise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='physician_expertise', to='Member.Expertises'),
        ),
        migrations.AlterField(
            model_name='physicians',
            name='prefix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='physician_prefix', to='Member.Prefixes'),
        ),
        migrations.AlterField(
            model_name='physicians',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='physician_user', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prefixes',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='profile_user', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
