# Generated by Django 2.0.7 on 2018-08-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='color',
            field=models.CharField(choices=[('RED', 'RED'), ('YELLOW', 'GREEN'), ('GREEN', 'GREEN'), ('BLUE', 'BLUE')], max_length=10),
        ),
    ]
