# Generated by Django 2.1.1 on 2018-09-29 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Member', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rtl_name', models.CharField(blank=True, default='منو', max_length=50, null=True)),
                ('index', models.IntegerField(default=0)),
                ('icon', models.PositiveIntegerField(blank=True, null=True)),
                ('icon_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocCatSubmenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('index', models.IntegerField(default=0)),
                ('rtl_name', models.CharField(blank=True, default='ساب منو', max_length=50, null=True)),
                ('icon', models.PositiveIntegerField(blank=True, null=True)),
                ('docCategories', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_menu', to='PatientDoc.DocCategories')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('site', models.CharField(choices=[('Nikan', 'Nikan Hospital'), ('Mehrad', 'Mehrad Hospital'), ('Milad', 'Milad Hospital')], max_length=30)),
                ('attachment', models.PositiveIntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PatientDoc.DocCategories')),
                ('doccatsubmenu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PatientDoc.DocCatSubmenu')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Member.Physicians')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rtl_name', models.CharField(blank=True, default='منو', max_length=50, null=True)),
                ('icon', models.PositiveIntegerField(blank=True, null=True)),
                ('icon_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('context', models.CharField(max_length=100000)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PatientDoc.HistoryCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_created_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
