# Generated by Django 2.0.7 on 2018-07-21 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PatientDoc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocCatSubmenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('index', models.IntegerField(default=0)),
                ('icon', models.PositiveIntegerField(blank=True, null=True)),
                ('docCategories', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PatientDoc.DocCategories')),
            ],
        ),
    ]
