# Generated by Django 2.0.7 on 2018-07-21 09:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('PatientDoc', '0003_auto_20180721_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='doccatsubmenu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='PatientDoc.DocCatSubmenu'),
            preserve_default=False,
        ),
    ]
