# Generated by Django 2.0.7 on 2018-08-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientDoc', '0004_documents_doccatsubmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='doccatsubmenu',
            name='icon_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
