# Generated by Django 2.0.7 on 2018-08-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientDoc', '0005_doccatsubmenu_icon_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doccatsubmenu',
            name='icon_name',
        ),
        migrations.AddField(
            model_name='doccategories',
            name='icon_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
