# Generated by Django 2.0.7 on 2018-09-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientDoc', '0006_auto_20180807_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='doccategories',
            name='rtl_name',
            field=models.CharField(default='تصویربــرداری', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doccatsubmenu',
            name='rtl_name',
            field=models.CharField(default='سونوگرافی', max_length=50),
            preserve_default=False,
        ),
    ]
